const SitemapPlugin = require('sitemap-webpack-plugin').default

const paths = [
    {
        path: '/',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/players',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/11',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/12',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/13',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/14',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/15',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/16',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/17',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/18',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/19',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/20',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/11/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/12/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/13/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/14/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/15/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/16/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/17/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/18/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/19/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/20/attacking',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/11/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/12/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/13/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/14/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/15/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/16/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/17/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/18/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/19/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/20/possession',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/11/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/12/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/13/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/14/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/15/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/16/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/17/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/18/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/19/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/20/defending',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/comparison/44/45',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/comparison/40/45',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/comparison/20',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
    {
        path: '/player/comparison',
        lastmod: new Date().toISOString().slice(0, 10),
        priority: 0.8,
        changefreq: 'hourly',
    },
]

module.exports = {
    configureWebpack: {
        plugins: [
            new SitemapPlugin({
                base: 'https://www.football-stats.uk',
                paths,
                options: {
                    filename: 'sitemap.xml',
                    lastmod: true,
                    changefreq: 'monthly',
                },
            }),
        ],
    },
}
